/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author 4dominic888
 */
public class vCrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form vCrearCuenta
     */
    public vCrearCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloCrearCuenta = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtRegistroNombre = new javax.swing.JTextField();
        lbApellidoPaterno = new javax.swing.JLabel();
        txtRegistroApellidoPaterno = new javax.swing.JTextField();
        lbApellidoMaterno = new javax.swing.JLabel();
        txtRegistroApellidoMaterno = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lbFechaDeNacimiento1 = new javax.swing.JLabel();
        cbRegistroSexo = new javax.swing.JComboBox<>();
        btnRegistrarse = new javax.swing.JButton();
        bg_CrearCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloCrearCuenta.setBackground(new java.awt.Color(255, 255, 255));
        lbTituloCrearCuenta.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        lbTituloCrearCuenta.setForeground(new java.awt.Color(204, 204, 204));
        lbTituloCrearCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloCrearCuenta.setText("Ingrese sus datos");
        getContentPane().add(lbTituloCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 70));

        lbNombre.setBackground(new java.awt.Color(255, 255, 255));
        lbNombre.setForeground(new java.awt.Color(204, 204, 204));
        lbNombre.setText("Nombre");
        getContentPane().add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtRegistroNombre.setBackground(new java.awt.Color(102, 102, 102));
        txtRegistroNombre.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtRegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 240, -1));

        lbApellidoPaterno.setBackground(new java.awt.Color(255, 255, 255));
        lbApellidoPaterno.setForeground(new java.awt.Color(204, 204, 204));
        lbApellidoPaterno.setText("Apellido paterno");
        getContentPane().add(lbApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtRegistroApellidoPaterno.setBackground(new java.awt.Color(102, 102, 102));
        txtRegistroApellidoPaterno.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtRegistroApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, -1));

        lbApellidoMaterno.setBackground(new java.awt.Color(255, 255, 255));
        lbApellidoMaterno.setForeground(new java.awt.Color(204, 204, 204));
        lbApellidoMaterno.setText("Apellido materno");
        getContentPane().add(lbApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txtRegistroApellidoMaterno.setBackground(new java.awt.Color(102, 102, 102));
        txtRegistroApellidoMaterno.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtRegistroApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, -1));

        lbSexo.setForeground(new java.awt.Color(204, 204, 204));
        lbSexo.setText("Sexo");
        getContentPane().add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jDateChooser1.setBackground(new java.awt.Color(102, 102, 102));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 240, -1));

        lbFechaDeNacimiento1.setForeground(new java.awt.Color(204, 204, 204));
        lbFechaDeNacimiento1.setText("Fecha de nacimiento");
        getContentPane().add(lbFechaDeNacimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        cbRegistroSexo.setBackground(new java.awt.Color(102, 102, 102));
        cbRegistroSexo.setForeground(new java.awt.Color(204, 204, 204));
        cbRegistroSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        getContentPane().add(cbRegistroSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 240, -1));

        btnRegistrarse.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrarse.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistrarse.setText("Registrarse");
        getContentPane().add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 240, 40));

        bg_CrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BG_InicioSesion.jpg"))); // NOI18N
        getContentPane().add(bg_CrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vCrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_CrearCuenta;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JComboBox<String> cbRegistroSexo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel lbApellidoMaterno;
    private javax.swing.JLabel lbApellidoPaterno;
    private javax.swing.JLabel lbFechaDeNacimiento1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTituloCrearCuenta;
    private javax.swing.JTextField txtRegistroApellidoMaterno;
    private javax.swing.JTextField txtRegistroApellidoPaterno;
    private javax.swing.JTextField txtRegistroNombre;
    // End of variables declaration//GEN-END:variables
}
